"use client";

import { motion } from "framer-motion";
import { FileText, ExternalLink } from "lucide-react";
import WestRewalkSection from "@/components/WestRewalkSection";

interface Chapter {
    slug: string;
    title: string;
}

interface AIPageContentProps {
    chapters: Chapter[];
}

const reports = [
    {
        title: "Traffic Study",
        description: "Preliminary analysis generated by a research agent. I used OpenClaw, Claude Code and Gemini CLI to create it.",
        date: "2026",
        link: "/ai/academic_research_report_revised.pdf"
    }
];

export default function AIPageContent({ chapters }: AIPageContentProps) {
    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    };

    return (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-12"
            >
                <h1 className="text-4xl font-serif font-bold mb-4">AI Research</h1>
                <p className="text-muted-foreground text-lg">
                    My playpen for AI applications.
                </p>
                <blockquote className="mt-6 border-l-4 border-primary pl-4 italic text-muted-foreground text-lg">
                    &quot;AI is a tool, not a replacement for human creativity and critical thinking.&quot;
                </blockquote>
            </motion.div>

            <div className="space-y-16">

                <WestRewalkSection chapters={chapters} />

                <section>
                    <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
                        <span className="w-8 h-1 bg-accent rounded-full inline-block"></span>
                        Reports
                    </h2>
                    <motion.div
                        variants={container}
                        initial="hidden"
                        animate="show"
                        className="space-y-6"
                    >
                        {reports.map((report, idx) => (
                            <motion.div key={idx} variants={item} className="bg-card border border-border/50 rounded-lg p-6 shadow-sm hover:shadow-md transition-shadow">
                                <h3 className="text-xl font-semibold mb-2">{report.title}</h3>
                                <p className="text-muted-foreground mb-3">{report.description}</p>
                                <div className="flex flex-wrap gap-2">
                                    <a
                                        href={report.link}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="inline-flex items-center text-sm font-medium text-primary hover:text-primary/80 bg-primary/5 px-3 py-1 rounded-full transition-colors"
                                    >
                                        PDF REPORT
                                        <ExternalLink className="ml-1 h-3 w-3" />
                                    </a>
                                </div>
                            </motion.div>
                        ))}
                    </motion.div>
                </section>
            </div>
        </div>
    );
}
